apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
      - name: logger
        image: busybox
        command: ["/bin/sh","-c"]
        args: ['while true; do echo "$(date) Log test entry"; sleep 5; done']
